version: '3.9'
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    command: ["npm", "run", "start:dev"]
    volumes: 
      - app-source:/usr/src/app
