version: '3.9'
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    command: ["npm", "run", "start:dev"]
    volumes: 
      - app-source:/usr/src/app
    depends_on:
      - mysql

  mongo:
    build:
      context: .
      dockerfile: .docker/mongo/Dockerfile
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
